services:
  db:
    image: postgres:alpine
    container_name: task_manager_db
    restart: always
    environment:
      POSTGRES_DB: task_manager_db
      POSTGRES_USER: task_user
      POSTGRES_PASSWORD: task_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - task_manager_network  # Ensure DB is in the network

  web:
    build: .
    container_name: django_app
    restart: always
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      DATABASE_NAME: task_manager_db  
      DATABASE_USER: task_user
      DATABASE_PASSWORD: task_password
      DATABASE_HOST: db  
      DATABASE_PORT: 5432
      DEBUG: "True"
    volumes:
      - .:/app
    networks:
      - task_manager_network  # Ensure Web is in the same network

volumes:
  postgres_data:

networks:
  task_manager_network:
    driver: bridge  # Ensure containers communicate
