services:
  db:
    image: postgres:alpine
    container_name: task_manager_db
    restart: always
    environment:
      POSTGRES_DB: task_manager_db
      POSTGRES_USER: task_user
      POSTGRES_PASSWORD: task_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U task_user -d task_manager_db"]
      interval: 10s
      retries: 5
      timeout: 5s
  web:
    build: .
    container_name: django_app
    restart: always
    depends_on:
      - db
    links:
      - db:db
    ports:
      - "8000:8000"
    environment:
      POSTGRES_DB: task_manager_db  
      POSTGRES_USER: task_user
      POSTGRES_PASSWORD: task_password
      DEBUG: "True"
    volumes:
      - .:/app
 # Ensure Web is in the same network
    extra_hosts:
      - "host.docker.internal:host-gateway"
volumes:
  postgres_data:

networks:
  task_manager_network:
    driver: bridge  # Ensure containers communicate
